--
-- Name: roles;  Type: INSERT DEFAULT ROLES; Schema: public; Owner: badreddine
--

INSERT INTO roles(name)
VALUES ('ROLE_CUSTOMER') ON CONFLICT DO NOTHING;
INSERT INTO roles(name)
VALUES ('ROLE_PROVIDER') ON CONFLICT DO NOTHING;
INSERT INTO roles(name)
VALUES ('ROLE_SUPER_ADMIN') ON CONFLICT DO NOTHING;